ServerEvents.tags("item", event => {
    let item_obliterator_items = [
        "mysticalagradditions:inferium_coal_block",
        "mysticalagradditions:prudentium_coal_block",
        "mysticalagradditions:tertium_coal_block",
        "mysticalagradditions:imperium_coal_block",
        "mysticalagradditions:supremium_coal_block",
        "mysticalagradditions:insanium_coal_block",
        "mysticalagradditions:inferium_coal",
        "mysticalagradditions:prudentium_coal",
        "mysticalagradditions:tertium_coal",
        "mysticalagradditions:imperium_coal",
        "mysticalagradditions:supremium_coal",
        "mysticalagradditions:insanium_coal",

        "mysticalagradditions:inferium_paxel",
        "mysticalagradditions:prudentium_paxel",
        "mysticalagradditions:tertium_paxel",
        "mysticalagradditions:imperium_paxel",
        "mysticalagradditions:supremium_paxel",
        "mysticalagradditions:insanium_paxel",
        "mysticalagradditions:awakened_supremium_paxel",

        "mysticalagriculture:inferium_furnace",
        "mysticalagriculture:prudentium_furnace",
        "mysticalagriculture:tertium_furnace",
        "mysticalagriculture:imperium_furnace",
        "mysticalagriculture:supremium_furnace",
        "mysticalagriculture:awakened_supremium_furnace",
        "mysticalagriculture:insanium_furnace",

        "mysticalagriculture:diamond_sickle",
        "mysticalagriculture:diamond_scythe",

        "mysticalagriculture:inferium_pickaxe",
        "mysticalagriculture:inferium_shovel",
        "mysticalagriculture:inferium_axe",
        "mysticalagriculture:inferium_hoe",
        "mysticalagriculture:inferium_bow",
        "mysticalagriculture:inferium_crossbow",
        "mysticalagriculture:inferium_sickle",
        "mysticalagriculture:inferium_scythe",
        "mysticalagriculture:inferium_helmet",
        "mysticalagriculture:inferium_chestplate",
        "mysticalagriculture:inferium_leggings",
        "mysticalagriculture:inferium_boots",

        "mysticalagriculture:prudentium_pickaxe",
        "mysticalagriculture:prudentium_shovel",
        "mysticalagriculture:prudentium_axe",
        "mysticalagriculture:prudentium_hoe",
        "mysticalagriculture:prudentium_bow",
        "mysticalagriculture:prudentium_crossbow",
        "mysticalagriculture:prudentium_sickle",
        "mysticalagriculture:prudentium_scythe",

        "mysticalagriculture:prudentium_helmet",
        "mysticalagriculture:prudentium_chestplate",
        "mysticalagriculture:prudentium_leggings",
        "mysticalagriculture:prudentium_boots",

        "mysticalagriculture:tertium_pickaxe",
        "mysticalagriculture:tertium_shovel",
        "mysticalagriculture:tertium_axe",
        "mysticalagriculture:tertium_hoe",
        "mysticalagriculture:tertium_bow",
        "mysticalagriculture:tertium_crossbow",
        "mysticalagriculture:tertium_sickle",
        "mysticalagriculture:tertium_scythe",

        "mysticalagriculture:tertium_helmet",
        "mysticalagriculture:tertium_chestplate",
        "mysticalagriculture:tertium_leggings",
        "mysticalagriculture:tertium_boots",

        "mysticalagriculture:imperium_pickaxe",
        "mysticalagriculture:imperium_shovel",
        "mysticalagriculture:imperium_axe",
        "mysticalagriculture:imperium_hoe",
        "mysticalagriculture:imperium_bow",
        "mysticalagriculture:imperium_crossbow",
        "mysticalagriculture:imperium_sickle",
        "mysticalagriculture:imperium_scythe",

        "mysticalagriculture:imperium_helmet",
        "mysticalagriculture:imperium_chestplate",
        "mysticalagriculture:imperium_leggings",
        "mysticalagriculture:imperium_boots",

        "mysticalagriculture:supremium_pickaxe",
        "mysticalagriculture:supremium_shovel",
        "mysticalagriculture:supremium_axe",
        "mysticalagriculture:supremium_hoe",
        "mysticalagriculture:supremium_bow",
        "mysticalagriculture:supremium_crossbow",
        "mysticalagriculture:supremium_sickle",
        "mysticalagriculture:supremium_scythe",

        "mysticalagriculture:supremium_helmet",
        "mysticalagriculture:supremium_chestplate",
        "mysticalagriculture:supremium_leggings",
        "mysticalagriculture:supremium_boots",

        "mysticalagriculture:awakened_supremium_pickaxe",
        "mysticalagriculture:awakened_supremium_shovel",
        "mysticalagriculture:awakened_supremium_axe",
        "mysticalagriculture:awakened_supremium_hoe",
        "mysticalagriculture:awakened_supremium_bow",
        "mysticalagriculture:awakened_supremium_crossbow",
        "mysticalagriculture:awakened_supremium_sickle",
        "mysticalagriculture:awakened_supremium_scythe",

        "mysticalagriculture:awakened_supremium_helmet",
        "mysticalagriculture:awakened_supremium_chestplate",
        "mysticalagriculture:awakened_supremium_leggings",
        "mysticalagriculture:awakened_supremium_boots",

        "mysticalagriculture:tinkering_table",
        "mysticalagriculture:unattuned_augment",
        "mysticalagriculture:absorption_i_augment",
        "mysticalagriculture:luck_i_augment",
        "mysticalagriculture:health_boost_i_augment",
        "mysticalagriculture:pathing_aoe_i_augment",
        "mysticalagriculture:nausea_resistance_augment",
        "mysticalagriculture:night_vision_augment",
        "mysticalagriculture:water_breathing_augment",
        "mysticalagriculture:absorption_ii_augment",
        "mysticalagriculture:jump_boost_i_augment",
        "mysticalagriculture:health_boost_ii_augment",
        "mysticalagriculture:speed_i_augment",
        "mysticalagriculture:mining_aoe_i_augment",
        "mysticalagriculture:tilling_aoe_i_augment",
        "mysticalagriculture:pathing_aoe_ii_augment",
        "mysticalagriculture:blindness_resistance_augment",
        "mysticalagriculture:absorption_iii_augment",
        "mysticalagriculture:luck_ii_augment",
        "mysticalagriculture:fire_resistance_augment",
        "mysticalagriculture:jump_boost_ii_augment",
        "mysticalagriculture:step_assist_augment",
        "mysticalagriculture:health_boost_iii_augment",
        "mysticalagriculture:strength_i_augment",
        "mysticalagriculture:speed_ii_augment",
        "mysticalagriculture:haste_i_augment",
        "mysticalagriculture:no_fall_damage_augment",
        "mysticalagriculture:slow_falling_augment",
        "mysticalagriculture:mining_aoe_ii_augment",
        "mysticalagriculture:attack_aoe_i_augment",
        "mysticalagriculture:tilling_aoe_ii_augment",
        "mysticalagriculture:pathing_aoe_iii_augment",
        "mysticalagriculture:weakness_resistance_augment",
        "mysticalagriculture:slowness_resistance_augment",
        "mysticalagriculture:absorption_iv_augment",
        "mysticalagriculture:poison_resistance_augment",
        "mysticalagriculture:jump_boost_iii_augment",
        "mysticalagriculture:health_boost_iv_augment",
        "mysticalagriculture:strength_ii_augment",
        "mysticalagriculture:speed_iii_augment",
        "mysticalagriculture:haste_ii_augment",
        "mysticalagriculture:mining_aoe_iii_augment",
        "mysticalagriculture:attack_aoe_ii_augment",
        "mysticalagriculture:tilling_aoe_iii_augment",
        "mysticalagriculture:pathing_aoe_iv_augment",
        "mysticalagriculture:mining_fatigue_resistance_augment",
        "mysticalagriculture:hunger_resistance_augment",
        "mysticalagriculture:absorption_v_augment",
        "mysticalagriculture:luck_iii_augment",
        "mysticalagriculture:wither_resistance_augment",
        "mysticalagriculture:health_boost_v_augment",
        "mysticalagriculture:strength_iii_augment",
        "mysticalagriculture:haste_iii_augment",
        "mysticalagriculture:flight_augment",
        "mysticalagriculture:mining_aoe_iv_augment",
        "mysticalagriculture:attack_aoe_iii_augment",
        "mysticalagriculture:tilling_aoe_iv_augment",

        "mysticalagriculture:rubber_essence",
        "mysticalagriculture:apatite_essence",
        "mysticalagriculture:tin_essence",
        "mysticalagriculture:zinc_essence",
        "mysticalagriculture:brass_essence",
        "mysticalagriculture:graphite_essence",
        "mysticalagriculture:invar_essence",
        "mysticalagriculture:mithril_essence",
        "mysticalagriculture:tungsten_essence",
        "mysticalagriculture:titanium_essence",
        "mysticalagriculture:chrome_essence",
        "mysticalagriculture:ruby_essence",
        "mysticalagriculture:sapphire_essence",
        "mysticalagriculture:peridot_essence",
        "mysticalagriculture:platinum_essence",
        "mysticalagriculture:iridium_essence",
        "mysticalagriculture:queens_slime_essence",
        "mysticalagriculture:hepatizon_essence",
        "mysticalagriculture:silicon_essence",
        "mysticalagriculture:pig_iron_essence",
        "mysticalagriculture:slimesteel_essence",
        "mysticalagriculture:amethyst_bronze_essence",
        "mysticalagriculture:bronze_essence",
        "mysticalagriculture:steel_essence",
        "mysticalagriculture:constantan_essence",
        "mysticalagriculture:electrum_essence",
        "mysticalagriculture:hop_graphite_essence",
        "mysticalagriculture:rose_gold_essence",
        "mysticalagriculture:manyullyn_essence",
        "mysticalagriculture:fluix_essence",
        "mysticalagriculture:sulfur_essence",
        "mysticalagriculture:saltpeter_essence",

        "mysticalagriculture:rubber_seeds",
        "mysticalagriculture:apatite_seeds",
        "mysticalagriculture:tin_seeds",
        "mysticalagriculture:zinc_seeds",
        "mysticalagriculture:brass_seeds",
        "mysticalagriculture:graphite_seeds",
        "mysticalagriculture:invar_seeds",
        "mysticalagriculture:mithril_seeds",
        "mysticalagriculture:tungsten_seeds",
        "mysticalagriculture:titanium_seeds",
        "mysticalagriculture:chrome_seeds",
        "mysticalagriculture:ruby_seeds",
        "mysticalagriculture:sapphire_seeds",
        "mysticalagriculture:peridot_seeds",
        "mysticalagriculture:platinum_seeds",
        "mysticalagriculture:iridium_seeds",
        "mysticalagriculture:queens_slime_seeds",
        "mysticalagriculture:hepatizon_seeds",
        "mysticalagriculture:silicon_seeds",
        "mysticalagriculture:pig_iron_seeds",
        "mysticalagriculture:slimesteel_seeds",
        "mysticalagriculture:amethyst_bronze_seeds",
        "mysticalagriculture:bronze_seeds",
        "mysticalagriculture:steel_seeds",
        "mysticalagriculture:constantan_seeds",
        "mysticalagriculture:electrum_seeds",
        "mysticalagriculture:hop_graphite_seeds",
        "mysticalagriculture:rose_gold_seeds",
        "mysticalagriculture:manyullyn_seeds",
        "mysticalagriculture:fluix_seeds",
        "mysticalagriculture:sulfur_seeds",
        "mysticalagriculture:saltpeter_seeds",

        "mysticalagradditions:inferium_apple",
        "mysticalagradditions:prudentium_apple",
        "mysticalagradditions:tertium_apple",
        "mysticalagradditions:imperium_apple",
        "mysticalagradditions:supremium_apple",
        "mysticalagradditions:insanium_apple",

        "waystones:sharestone",
        "waystones:warp_plate",
        "waystones:portstone",
        "waystones:white_sharestone",
        "waystones:orange_sharestone",
        "waystones:magenta_sharestone",
        "waystones:light_blue_sharestone",
        "waystones:yellow_sharestone",
        "waystones:lime_sharestone",
        "waystones:pink_sharestone",
        "waystones:gray_sharestone",
        "waystones:light_gray_sharestone",
        "waystones:cyan_sharestone",
        "waystones:purple_sharestone",
        "waystones:blue_sharestone",
        "waystones:brown_sharestone",
        "waystones:green_sharestone",
        "waystones:red_sharestone",
        "waystones:black_sharestone",
        "waystones:warp_stone",

        "ae2:meteorite_compass",

        "hoppergadgetry:chute",
        "hoppergadgetry:chute_minecart",

        "mysticalagriculture:enchanter", 
        "mysticalagriculture:seed_reprocessor",

        "tconstruct:clear_item_frame",
        "ae2:sky_stone_tank",
        
        "brewinandchewin:sweet_berry_jam",
        "brewinandchewin:glow_berry_marmalade",
        "brewinandchewin:apple_jelly",

        "vintagedelight:apple_sauce_bottle",
        "vintagedelight:gearo_berry_jam_bottle",
        "vintagedelight:sweet_berry_jam_bottle",
        "vintagedelight:glow_berry_jam_bottle",
        "vintagedelight:pepper_jam_bottle",
        "vintagedelight:relish_bottle",
        "vintagedelight:apple_sauce_mason_jar", 
        "vintagedelight:sweet_berry_mason_jar", 
        "vintagedelight:glow_berry_mason_jar",

        "vintagedelight:cheese_mold",
        "vintagedelight:cheese_curds",
        "vintagedelight:cheese_slice",
        "vintagedelight:cheese_wheel",
        "tconstruct:cheese_ingot",
        "tconstruct:cheese_block"
    ] 

    event.removeAllTagsFrom(item_obliterator_items)
    event.add("c:hidden_from_recipe_viewers", item_obliterator_items)
})