ServerEvents.recipes(event => {
    function removeRecipe(itemId) {
        event.remove({output: itemId})
    }
    
    removeRecipe("minecraft:wooden_pickaxe")
    removeRecipe("minecraft:stone_pickaxe")
    removeRecipe("minecraft:iron_pickaxe")
    removeRecipe("minecraft:golden_pickaxe")
    removeRecipe("minecraft:diamond_pickaxe")
    removeRecipe("minecraft:netherite_pickaxe")
    removeRecipe("ae2:certus_quartz_pickaxe")
    removeRecipe("ae2:nether_quartz_pickaxe")
    removeRecipe("ae2:fluix_pickaxe")
    removeRecipe("immersiveengineering:pickaxe_steel")

    removeRecipe("minecraft:wooden_axe")
    removeRecipe("minecraft:stone_axe")
    removeRecipe("minecraft:iron_axe")
    removeRecipe("minecraft:golden_axe")
    removeRecipe("minecraft:diamond_axe")
    removeRecipe("minecraft:netherite_axe")
    removeRecipe("immersiveengineering:axe_steel")
    removeRecipe("ae2:certus_quartz_axe")
    removeRecipe("ae2:nether_quartz_axe")
    removeRecipe("ae2:fluix_axe")

    removeRecipe("minecraft:wooden_hoe")
    removeRecipe("minecraft:stone_hoe")
    removeRecipe("minecraft:iron_hoe")
    removeRecipe("minecraft:golden_hoe")
    removeRecipe("minecraft:diamond_hoe")
    removeRecipe("minecraft:netherite_hoe")
    removeRecipe("ae2:fluix_hoe")
    removeRecipe("ae2:nether_quartz_hoe")
    removeRecipe("ae2:certus_quartz_hoe")
    removeRecipe("immersiveengineering:hoe_steel")

    removeRecipe("minecraft:wooden_shovel")
    removeRecipe("minecraft:stone_shovel")
    removeRecipe("minecraft:iron_shovel")
    removeRecipe("minecraft:golden_shovel")
    removeRecipe("minecraft:diamond_shovel")
    removeRecipe("minecraft:netherite_shovel")
    removeRecipe("ae2:certus_quartz_shovel")
    removeRecipe("ae2:nether_quartz_shovel")
    removeRecipe("ae2:fluix_shovel")
    removeRecipe("immersiveengineering:shovel_steel")

    removeRecipe("minecraft:wooden_sword")
    removeRecipe("minecraft:stone_sword")
    removeRecipe("minecraft:iron_sword")
    removeRecipe("minecraft:golden_sword")
    removeRecipe("minecraft:diamond_sword")
    removeRecipe("minecraft:netherite_sword")
    removeRecipe("ae2:certus_quartz_sword")
    removeRecipe("ae2:nether_quartz_sword")
    removeRecipe("ae2:fluix_sword")
    removeRecipe("immersiveengineering:sword_steel")

    removeRecipe("minecraft:iron_helmet")
    removeRecipe("minecraft:iron_chestplate")
    removeRecipe("minecraft:iron_leggings")
    removeRecipe("minecraft:iron_boots")
    removeRecipe("minecraft:netherite_helmet")
    removeRecipe("minecraft:netherite_chestplate")
    removeRecipe("minecraft:netherite_leggings")
    removeRecipe("minecraft:netherite_boots")
    removeRecipe("minecraft:golden_helmet")
    removeRecipe("minecraft:golden_chestplate")
    removeRecipe("minecraft:golden_leggings")
    removeRecipe("minecraft:golden_boots")
    removeRecipe("minecraft:diamond_helmet")
    removeRecipe("minecraft:diamond_chestplate")
    removeRecipe("minecraft:diamond_leggings")
    removeRecipe("minecraft:diamond_boots")

    removeRecipe("immersiveengineering:armor_steel_chestplate")
    removeRecipe("immersiveengineering:armor_steel_helmet")
    removeRecipe("immersiveengineering:armor_steel_leggings")
    removeRecipe("immersiveengineering:armor_steel_boots")
})